workspace(name = "lint_example")

local_repository(
  name = "apple_rules_lint",
  path = "..",
)

load("@apple_rules_lint//lint:repositories.bzl", "lint_deps")

lint_deps()

load("@apple_rules_lint//lint:setup.bzl", "lint_setup")

lint_setup()

load("@apple_rules_lint//lint:workspace.bzl", "register_linters")

register_linters({
#    "lint_example": "//:default_config",
})
