workspace(name = "lint_example")

local_repository(
    name = "apple_rules_lint",
    path = "..",
)

load("@apple_rules_lint//lint:repositories.bzl", "lint_deps")

lint_deps()

load("@apple_rules_lint//lint:setup.bzl", "lint_setup")

lint_setup({
    #    "lint_example": "//:default_config",
})
