name: Run BCR tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  bcr_tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    name: Run BCR tests (${{ matrix.os }})
    env:
      BAZELISK_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - name: Run tests
        env:
          USE_BAZEL_VERSION: last_green
        working-directory: ./tests/bcr
        run: bazelisk test //...
